## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 46.1.1

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

services:
  app:
    image: markoshust/magento-nginx:1.24-0
    ports:
      - "8080:8000"
      - "8443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
#      - ./src/vendor/nosto/module-nostotagging:/var/www/html/vendor/nosto/module-nostotagging
#      - ./src/vendor/nosto/module-nostotagging-cmp:/var/www/html/vendor/nosto/module-nostotagging-cmp
#      - ./src/vendor/nosto/module-nosto-msi:/var/www/html/vendor/nosto/module-nosto-msi
#      - ./src/vendor/nosto/php-sdk:/var/www/html/vendor/nosto/php-sdk
#      - ./src/generated:/var/www/html/generated
    extra_hosts: &appextrahosts
      - "magento245.dev.nos.to:172.17.0.1"
      - "my.dev.nos.to:192.168.65.254"
      - "selenium:172.23.0.8"
      ## Selenium support, replace "magento.test" with URL of your site
      #- "magento.test:172.17.0.1"
      ## Linux, uncomment for Xdebug capabilities:
      #- "host.docker.internal:host-gateway"

#  mage-logs:
#    image: markoshust/magento-php:8.3-fpm-2
#    volumes: *appvolumes
#    extra_hosts: *appextrahosts
#    env_file: env/phpfpm.env
#    working_dir: /var/www/html
#    entrypoint:
#      - bash
#      - -e
#      - -c
#      - >
#        tail -f var/log/*
  phpfpm:
    image: markoshust/magento-php:8.3-fpm-2
    volumes: *appvolumes
    env_file: env/phpfpm.env
    extra_hosts: *appextrahosts

  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  ## If you wish to use MySQL, comment out the mariadb db image above and
  ## uncomment this block.
  #db:
  #  image: mysql:8.0
  #  command:
  #    --max_allowed_packet=64M
  #    --optimizer_use_condition_selectivity=1
  #    --optimizer_switch="rowid_filter=off"
  #  ports:
  #    - "3306:3306"
  #  env_file: env/db.env
  #  volumes:
  #    - dbdata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
#    ports:
#      - "6379:6379"

  opensearch:
    image: markoshust/magento-opensearch:2.12-0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      ## Uncomment the following line to increase the virtual memory map count
  #   - "max_map_count=262144"

  ## If you wish to use Elasticsearch, comment out opensearch image above and
  ## uncomment this block. Do the same in the composer.healthcheck.yaml file.
  # Additionally, if you are performing the manual setup, you will need to
  # update the bin/setup command to use the $ES_HOST variable as the value for
  # the --elasticsearch-host argument passed to bin/magento setup:install.
  #elasticsearch:
  #  image: markoshust/magento-elasticsearch:8.13-0
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"
  #  env_file: env/elasticsearch.env
  #  environment:
  #    - "discovery.type=single-node"
  #    ## Avoid test failures due to small disks
  #    ## More info at https://github.com/markshust/docker-magento/issues/488
  #    - "cluster.routing.allocation.disk.threshold_enabled=false"
  #    - "index.blocks.read_only_allow_delete"
  #    ## Uncomment the following line to increase the virtual memory map count
  #    - "max_map_count=262144"

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.12-0
    ports:
      - "15673:15672"
#      - "5673:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
#    ports:
#      - "1080:1080"
  
  ## Cloudflare tunnel support, uncomment to enable
  #tunnel:
  #  container_name: cloudflared-tunnel
  #  image: cloudflare/cloudflared:latest
  #  command: tunnel run
  #  env_file: env/cloudflare.env
  
  ## Blackfire support, uncomment to enable
  #blackfire:
  #  image: blackfire/blackfire:2
  #  ports:
  #    - "8307"
  #  env_file: env/blackfire.env

  ## Selenium support, uncomment to enable
  #selenium:
  #  image: selenium/standalone-chrome-debug:3.8.1
  #  ports:
  #    - "5900:5900"
  #  extra_hosts: *appextrahosts
  # # Blackfire support, uncomment to enable
  # blackfire:
  #  image: blackfire/blackfire:2
  #  ports:
  #    - "8307"
  #  env_file: env/blackfire.env

  #   Selenium support, uncomment to enable
  #  selenium:
  ##    image: selenium/standalone-chrome-debug
  #    image: seleniarm/standalone-chromium
  ##    image: selenium/standalone-chrome
  #    ports:
  #      - "5900:5900"
  #      - "4444:4444"
  #    extra_hosts: *appextrahosts

  #  composer:
  #    image: markoshust/magento-php:8.3-fpm-2
  #    volumes:
  #      - type: bind
  #        source: ./src/vendor/nosto/module-nostotagging
  #        target: /var/www/html/vendor/nosto/module-nostotagging
  #      - type: bind
  #        source: ~/.composer/auth.json
  #        # source: ./src/var/composer_home/auth.json
  #        target: /var/www/.composer/auth.json
  #    working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #    # environment:
  #      # - "COMPOSER_DISABLE_NETWORK=1"
  #    entrypoint:
  #      - bash
  #      - -e
  #      - -c
  #      - >
  #        case $$0 in
  #           install)
  #             composer "$$0" --no-interaction "$$@";
  #             ;;
  #           *)
  #             composer "$$0" "$$@"
  #             ;;
  #        esac;
  #
  #  composer-sdk:
  #    image: markoshust/magento-php:8.3-fpm-2
  #    volumes:
  #      - type: bind
  #        source: ./src/vendor/nosto/php-sdk
  #        target: /var/www/html/vendor/nosto/php-sdk
  #      - type: bind
  #        source: ~/.composer/auth.json
  #        target: /var/www/.composer/auth.json
  #    working_dir: /var/www/html/vendor/nosto/php-sdk
  #    entrypoint:
  #      - bash
  #      - -e
  #      - -c
  #      - >
  #        case $$0 in
  #           install)
  #             composer "$$0" --no-interaction "$$@";
  #             ;;
  #           *)
  #             composer "$$0" "$$@"
  #             ;;
  #        esac;
  #  tests:
  #    image: markoshust/magento-php:8.3-fpm-2
  #    volumes:
  #      - type: bind
  #        source: ./src/vendor/nosto/php-sdk
  #        target: /var/www/html/vendor/nosto/php-sdk
  #    working_dir: /var/www/html/vendor/nosto/php-sdk
  #    entrypoint:
  #      - bash
  #      - -e
  #      - -c
  #      - >
  #        ./vendor/bin/codecept run --xml "$$0" "$$@"
  # psalm:
  #   image: markoshust/magento-php:8.3-fpm-2
  #   volumes:
  #     - type: bind
  #       source: ./src/vendor/nosto/module-nostotagging
  #       target: /var/www/html/vendor/nosto/module-nostotagging
  #     - type: bind
  #       source: ~/.composer/auth.json
  #       # source: ./src/var/composer_home/auth.json
  #       target: /var/www/.composer/auth.json
  #   working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #   # environment:
  #     # - "COMPOSER_DISABLE_NETWORK=1"
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       ./vendor/bin/psalm "$$0" "$$@";


  # phpcs-mage:
  #   image: markoshust/magento-php:8.3-fpm-2
  #   volumes:
  #     - type: bind
  #       source: ./src/vendor/nosto/module-nostotagging
  #       target: /var/www/html/vendor/nosto/module-nostotagging
  #     - type: bind
  #       source: ./src/vendor/nosto/module-nostotagging
  #       target: /var/www/.composer/auth.json
  #   working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/ && vendor/bin/phpcs -i && vendor/bin/phpcs --standard=Magento2 --parallel=5
  #  phpcs:
  #    image: markoshust/magento-php:8.3-fpm-2
  #    volumes:
  #      - type: bind
  #        source: ./src/vendor/nosto/module-nostotagging
  #        target: /var/www/html/vendor/nosto/module-nostotagging
  #    working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #    entrypoint:
  #      - bash
  #      - -e
  #      - -c
  #      - >
  #        ./vendor/bin/phpcs --standard=ruleset.xml --report=checkstyle
  # phpcbf-mage:
  #   image: markoshust/magento-php:8.3-fpm-2
  #   volumes:
  #     - type: bind
  #       source: ./src/vendor/nosto/module-nostotagging
  #       target: /var/www/html/vendor/nosto/module-nostotagging
  #   working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       vendor/bin/phpcbf --config-set installed_paths ../../magento/magento-coding-standard/ && vendor/bin/phpcbf -i && vendor/bin/phpcbf --standard=Magento2 --parallel=5 --file-list=fileListPhpcs
  #  phpunit:
  #    image: markoshust/magento-php:8.3-fpm-2
  #    volumes:
  #      - type: bind
  #        source: ./src/vendor/nosto/module-nostotagging
  #        target: /var/www/html/vendor/nosto/module-nostotagging
  #    working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #    entrypoint:
  #      - bash
  #      - -e
  #      - -c
  #      - >
  #        ./vendor/bin/phpunit "$$0" "$$@"

  # phan:
  #   image: markoshust/magento-php:8.3-fpm-2 # MISSING AST
  #   volumes:
  #     - type: bind
  #       source: ./src/vendor/nosto/module-nostotagging
  #       target: /var/www/html/vendor/nosto/module-nostotagging
  #   working_dir: /var/www/html/vendor/nosto/module-nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       ./vendor/bin/phan --config-file=phan.php --output-mode=checkstyle
  # Api, Block, Console, Controller, Cron, CustomerData, Exception, Helper, Logger, Model, Observer, Plugin, Util
  # vendor/bin/phpcs --standard=Magento2 app/code/Xigen/Extension

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
